name: "Gradle Build Action"
description: "Build Java projects using Gradle"

inputs:
  java_version:
    description: "Java version to use"
    required: false
    default: "21"
  java_distribution:
    description: "JDK distribution to use"
    required: false
    default: "corretto"

runs:
  using: "composite"
  steps:
    - name: Log version
      shell: bash
      run: echo "Using action template v1.0.1"

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Java ${{ inputs.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}

    - name: Grant execute permission for Gradlew
      shell: bash
      run: chmod +x ./gradlew

    - name: Build with Gradle
      shell: bash
      run: ./gradlew ${{ inputs.gradle_tasks }}
